# Proposal

## Research topic
  
In this project, we are going to conduct a research on the trip records of yellow-cab taxi and for-hire vehicles in New York City using the data collected by the NYC Taxi & Limousine Commission. With the help of cross-examining the datasets and doing analysis, our team’s goals are to generate meaningful visualizations, discover and deliver profound and useful insights. Our two main research directions are the passengers’ behaviors and the stories behind them (their communities, reasons to travel, etc.)  The project will be separated into several research questions including but not limited to:  
  
- What time of the day has the highest demand? 
- Which areas are popular destinations on weekends? 
- What is the most likely time period for a long distance ride?
- Do areas with high yellow-cab ride numbers also have high for-hire vehicle ride numbers?
- What are the areas that give a high tip amount (between 30% and 50%)?
- For each type of vehicle, which airport do their passengers usually prefer to go to?  
- For those passengers who arrived at the airports, what type of vehicle they preferred to take?
  
Through our extensive data analysis and visualizations, we hope to effectively deliver our insights to our audience regarding passengers’ behaviors and different communities/regions in NYC.  

## Data availability
  
### Data Source
  
To analyze passenger behaviors , we use trip records data from The New York City Taxi and Limousine Commision (TLC), the agency of licensing and regulating taxi and for-hire vehicles (FHV). In collaboration with authorized technology providers, TLC collects comprehensive data including trip records, drivers related data, active/inactive vehicle data, etc. Since this project aims to analyze passengers behavior, we would mainly focus on the trip records dataset.  

Trip records data can be divided into two categories: yellow and green taxi trip records, and for-hire vehicle (FHV) trip records.  

- Yellow taxis are the only vehicles permitted by TLC to respond to street hail in all five boroughs in NYC. Green taxis are allowed to provide prearranged service and respond to street hails only in the area of northern Manhattan (above E 96th St and W 110th St) and in the outer boroughs.  For yellow and green taxi trip records data, TLC collects them from technology providers authorized under the Taxicab & Livery Passenger Enhancement Programs (TPEP/LPEP). TLC cannot guarantee the accuracy of these data.

- For-hire vehicle (FHV) trip records include data from community livery bases, luxury limousine bases, black car bases and high-volume for-hire vehicle bases (bases for companies, like Uber and Lyft, dispatching over 10,000  trips per day).  FHV trip records are generated from FHV Trip Record submissions made by TLC-licensed bases. TLC cannot guarantee the accuracy and completeness of trip records submitted by bases. However, TLC examines these records and appropriately takes actions to make records data as complete and accurate as possible.  

TLC publishes four separate trip records datasets per month: “yellow taxi trip records”, “green taxi trip records”, “for-hire vehicle trip records” and “high-volume for-hire vehicle trip records”. In this project, we temporarily choose three datasets: the trip records of yellow taxi, green taxi and high-volume FHV. For the reason that the “for-hire vehicle trip records” dataset only has 7 columns whereas others have about 20 columns, we hold the opinion that this dataset lacks information and decide to abandon this dataset.  

In consideration of the similarity between yellow taxi and green taxi, as well as the relatively small size of green taxi data, we may combine the trip records data of these two types of taxi together as a big dataset called “yellow/green taxi trip records”  

The timeframe of trip records data will be one month. So far, the latest dataset provided by TLC is the trip records data of June 2022.  

Since trip records also contain simple geographical location information, such as Taxi Zone, to record starting area and destination area of a trip, we need a Taxi Zone Lookup Table, provided by TLC, as the ancillary data.  

### Frequency of Updates
  
TLC will publish trip records data monthly, with two months delay. 

### Format of Data

The trip records dataset files retrieved from TLC official website are stored in PARQUET format.  

In each trip records dataset, one row represents a single trip made by a TLC-licensed vehicle, recording the information of pick-up and drop-off locations and dates, trip distance, trip fare amount, tip amount and other useful information.  

The Taxi Zone Lookup Table is stored in CSV format. It linked pick-up and drop-off location id with the geographic location.

### Import Data

Since our trip records datasets are provided in Parquet files, we use read_parquet() from the arrow package in R to load data.  

For the Taxi Zone Lookup Table, we use read_csv() from readr package to load Taxi Zone data and join it with trip records data to retrieve location information.  

### Data Source Links

TLC Trip Record Data Website:   
[https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page)  
  
Yellow Taxi Trip Records:  
  
- [2022 June](https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-06.parquet)
  
Green Taxi Trip Records:  
  
- [2022 June](https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-06.parquet)
  
High Volume For-Hire Vehicle Trip Records:  
  
- [2022 June](https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2022-06.parquet)
  
Taxi Zone Lookup Table:  
[https://d37ci6vzurychx.cloudfront.net/misc/taxi+_zone_lookup.csv](https://d37ci6vzurychx.cloudfront.net/misc/taxi+_zone_lookup.csv)

We will email to research@tlc.nyc.gov if we have questions or need more information about data.


